### PR TITLE
Apply assorted ruff rules

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**

### CODE REVIEW

**Review by FrancescAlted — COMMENTED** [review]
I don't quite understand why double quotes (") should be used instead of (') ones.  Why is this happening?  Also, the PR does not merge cleanly; can this be fixed?

Other than that, I'm fine with this.

**Comment by DimitriPapadopoulos** [comment]
I have left the default value `"double"` of the [`quote-style`](https://docs.astral.sh/ruff/settings/#format_quote-style) setting of the ruff formatter. The reason is that the whole code base uses double quotes except for a few places.

I can change to `"preserve"` if you'd rather the formatter not mess with the quote style.

**Comment by DimitriPapadopoulos** [comment]
I still need to fix `Python wheels / Build sdist`.

**Review by FrancescAlted — APPROVED** [review]
LGTM

**Comment by FrancescAlted** [comment]
Ok.  I merged this.  Yeah, is not easy to deal with the quote ambiguity in Python.  Your suggested approach seems sensible to me.  Thanks!

**Pull request merged**
