### PR TITLE
First introduction of pow operator

### PR DESCRIPTION
**Pull request by omaech**
This is still work in progress

### CODE REVIEW

**Comment by FrancescAlted** [comment]
That's pretty good.  Now, you have to make the test working when using `NDArray` objects, and not just `LazyExpr` instances.

**Comment by FrancescAlted** [comment]
Cool.  Now, it would be nice if you can add support for `__iadd__`, `__isub__`, `__imul__` and `__itruediv__` for *both* `NDArray` and `LazyExpr`.  Add tests for both of these `NDArray` and `LazyExpr` objects too.

**Comment by omaech** [comment]
I did the work in the previus commit. Would that be good enough?

**Comment by FrancescAlted** [comment]
That's good!  Now, as there are much more fixtures, and to prevent an explosion in tests, could you fusion the new tests for `__iXXX__` special functions in a single one?

**Comment by FrancescAlted** [comment]
Let's merge this now and continue improving later.

**Pull request merged**
