### PR TITLE
Remove pkgconfig/blosc2.pc from python installation

### LINKED ISSUE #105: `setup.py` → `pyproject.toml`
Python packaging evolves. The executable `setup.py` should be replaced by a declarative `pyproject.toml` for compliance with [PEP 517](https://peps.python.org/pep-0517/), [PEP 518](https://peps.python.org/pep-0518/), [PEP 660](https://peps.python.org/pep-0660/), etc.

Note that this is a breaking change, because `pyproject.toml` requires a recent version of `pip` and `setuptools`. Using a recent version of these tools might not be possible in some contexts where updating from internet is impossible, such as building RPM or DEB packages.

### LINKED ISSUE #110: distributed `blosc2.pc` has wrong prefix
The distributed `blosc2.pc` includes the wrong prefix. This obviously complicates anything that tries to use `pkg-config` to detect `blsoc2`.  Basically whatever temporary directory `python-blosc2` is installed to during the build process becomes the prefix.

The two wheels I've checked have:
 - macOS-arm64: `prefix=/Users/runner/work/python-blosc2/python-blosc2/_skbuild/macosx-11.0-arm64-3.11/cmake-install`
 - linux-x86_64: `prefix=/project/_skbuild/linux-x86_64-3.10/cmake-install`

When installing from source you get something akin to:
 - `prefix=/Users/nega/Downloads/python-blosc2/_skbuild/macosx-13.0-arm64-3.11/cmake-install`

Three ways I see to address this issue are
 1. during the build process, edit the `build2.pc` after its creation
 2. take advantage of DESTDIR during the build of `c-blosc2`
 3. remove `build2.pc` outright

See also PyTables/PyTables#998

The following is a demonstration of installing `python-blosc2` into a clean virtual env creatively called "blosc2".

----
```
❯ python -m venv blosc2

❯ . blosc2/bin/activate

blosc2 ❯ pip3 install --upgrade blosc2
[... 8< ...]
Successfully installed blosc2-2.2.1 markdown-it-py-2.2.0 mdurl-0.1.2 msgpack-1.0.5 ndindex-1.7 numpy-1.24.3 py-cpuinfo-9.0.0 pygments-2.15.1 rich-13.3.5

blosc2 ❯ find ./blosc2 -name blosc2.pc
./blosc2/lib/pkgconfig/blosc2.pc

blosc2 ❯ cat ./blosc2/lib/pkgconfig/blosc2.pc
prefix=/Users/runner/work/python-blosc2/python-blosc2/_skbuild/macosx-11.0-arm64-3.11/cmake-install
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
sharedlibdir=${libdir}
includedir=${prefix}/include

Name: blosc2
Description: A blocking, shuffling and lossless compression library
URL: https://blosc.org/
Version: 2.9.1

Requires:
Libs: -L${libdir} -L${sharedlibdir} -lblosc2
Cflags: -I${includedir}

blosc2 ❯ find blosc2 -name libblosc2\*
blosc2/lib/libblosc2.2.dylib
blosc2/lib/libblosc2.a
blosc2/lib/libblosc2.2.9.1.dylib
blosc2/lib/libblosc2.dylib
```

### PR DESCRIPTION
**Pull request by bnavigator**
Fixes #110
Fixes #105 (to the extend that scikit-build allows it at the present time)

### CODE REVIEW

**Comment by bnavigator** [comment]
Relevant discussion: https://github.com/scikit-build/scikit-build/issues/500, https://github.com/uber/h3-py/issues/125#issuecomment-641717494

**Comment by FrancescAlted** [comment]
I have tested this locally, and it does not include the blosc2.pc anymore, so this looks good to me.  Thanks!

**Comment by FrancescAlted** [comment]
Python-Blosc2 2.2.2 is out.  Tell me if that fixes your issues.

**Comment by bnavigator** [comment]
> Python-Blosc2 2.2.2 is out. Tell me if that fixes your issues.

Not mine, but @nega0's in https://github.com/PyTables/PyTables/issues/998

**Comment by nega0** [comment]
Other than the `blosc2.pc` file getting left be on upgrade, I'm good to go. I don't have an opinion on what to do about that. The simple answer might be just do document that users need to remove it themselves if they have some kind of conflict.

**Comment by FrancescAlted** [comment]
> Other than the `blosc2.pc` file getting left be on upgrade, I'm good to go. I don't have an opinion on what to do about that. The simple answer might be just do document that users need to remove it themselves if they have some kind of conflict.

Yeah, that's a good point.  Well, at least this is kind of documented here, in case affected people would google for this issue.

**Pull request merged**
