### PR TITLE
Allow linking to system c-blosc2 shared library

### LINKED ISSUE #15: Python-blosc2 should be linked to system-installed blocsc2 shared library by default

### PR DESCRIPTION
**Pull request by bnavigator**
Fixes #15, based on https://github.com/Blosc/python-blosc2/commit/a1e419ddc9773ab6cc80c397e39935e9b6b76ded by @ArchangeGabriel.

### CODE REVIEW

**Comment by FrancescAlted** [comment]
LGTM.  Thanks @bnavigator !

**Review by FrancescAlted — COMMENTED** [review]
LGTM

**Comment by BwL1289** [comment]
@bnavigator thanks for this PR! I think docs could be improved on how to enable `USE_SYSTEM_BLOSC2`. In `python-blosc` you can enable it via an environment variable `USE_SYSTEM_BLOSC` in `setup.py` that's propagated to `CMakeLists.txt` when installed via `pip`.

I know there's an example [here](https://github.com/Blosc/python-blosc2/blob/v2.7.0/.guix/modules/python-blosc2-package.scm#L91C40-L91C57) on how to pass but might be cleaner to do via an environment variable in `setup.py`.

**Comment by BwL1289** [comment]
For anyone who finds this, `skbuild` has built in options for this. An example may be:

```
CMAKE_ARGS="-DUSE_SYSTEM_BLOSC2=YES" pip3 install blosc2 --no-deps --no-build-isolation --no-binary :all: --verbose --no-cache-dir
```

**Pull request merged**
