### PR TITLE
Enforce ruff/mccabe rule (C90)

### LINKED ISSUE #310: McCabe complexity
I just noticed in #309 that we did not enable a ruff equivalent to the [`max-complexity`](https://flake8.pycqa.org/en/7.1.0/user/options.html#cmdoption-flake8-max-complexity) option of flake8.

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Fixes #310.

Use the default value of the maximum McCabe complexity: 10

It looks like some functions became too complex after disabling flake8. How to handle that? Modify these functions? Disable `C901` for these functions?

### CODE REVIEW

**Comment by FrancescAlted** [comment]
Interesting. For the time being, I'd prefer to ignore  `C901` on affected functions (or relax maximum McCabe complexity).

**Comment by FrancescAlted** [comment]
BTW, thanks for all the careful work @DimitriPapadopoulos !  The devil is in the details, so much appreciated.

**Comment by DimitriPapadopoulos** [comment]
Existing issues ignored with `# noqa: C901`.

**Comment by FrancescAlted** [comment]
Sorry, same here.  Can you rebase this?

**Comment by DimitriPapadopoulos** [comment]
Please merge #312 first to fix CI issues. Then let me rebase this once again.

**Comment by FrancescAlted** [comment]
I am not sure I like McCabe complexity be so picky with some existing functions, but we will manage (I hope).

**Comment by FrancescAlted** [comment]
Thanks @DimitriPapadopoulos !

**Comment by DimitriPapadopoulos** [comment]
Or we can disable the rule. I've only added it because of the existing `.flake8` file.

**Pull request merged**
